// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTestTaskData;

#nullable disable

namespace SmartTestTaskData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230217140005_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartTestTaskModel.EquipmentPlacementContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionPremisesId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfEquipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionPremisesId");

                    b.HasIndex("TypeOfEquipmentId");

                    b.ToTable("EquipmentPlacementContract");
                });

            modelBuilder.Entity("SmartTestTaskModel.ProductionPremises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SpaceForEquipment")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProductionPremises");
                });

            modelBuilder.Entity("SmartTestTaskModel.TypeOfEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfEquipment");
                });

            modelBuilder.Entity("SmartTestTaskModel.EquipmentPlacementContract", b =>
                {
                    b.HasOne("SmartTestTaskModel.ProductionPremises", "ProductionPremises")
                        .WithMany()
                        .HasForeignKey("ProductionPremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTestTaskModel.TypeOfEquipment", "TypeOfEquipment")
                        .WithMany()
                        .HasForeignKey("TypeOfEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionPremises");

                    b.Navigation("TypeOfEquipment");
                });
#pragma warning restore 612, 618
        }
    }
}
